"""MAIK v2.0 — Full test: Multi-CEO architecture + all 21 sections."""
import sys; sys.path.insert(0, '.')
import time, json, hashlib

from config import (cfg, corp, experts, council, ExecutiveCouncil, CEOProfile, CEO_FULL, CEO_LIGHT,
                    TokenBudget, Corporate, safety_cfg, memory_cfg, cognitive_cfg, evolution_cfg)
from blackboard import blackboard, internal_notes
from router_engine import route, clear_cache, cache_stats, ceo_routing_log
from tree_engine import execute, get_execution_log, ceo_execution_breakdown
from learn_engine import learn, get_stats
from safety_engine import (stop_light, kill_switch, _safety_triad, monotonic, anti_pattern,
                           CircuitBreaker, SafetyTriad, MonotonicConfidence, StopLight)
from memory_engine import l1_memory, l2_memory, l3_memory, thought_vdb, L1Memory, L2Memory
from scheduler_engine import scheduler, CostAwareScheduler
from cognitive_engine import incubation, abductor, analogizer, wanderer, chunker
from corporate_engine import corp_library, perm_system, CorporateLibrary, PermissionSystem
from purity_filter import purity, PurityFilter
from meta_controller import meta_agent, state_machine, MetaAgent
from evolution_engine import pbt, reward_shaper, PBTEngine, RewardShaper
from boolean_engine import voter, AgentGate, GateOp, AgentCircuit, NeuralVoter
from expert_bridge import expert_bridge

passed = 0; failed = 0
def check(name, condition, detail=""):
    global passed, failed
    if condition: passed += 1; print(f"  PASS: {name}")
    else: failed += 1; print(f"  FAIL: {name} - {detail}")

print("=" * 64)
print("MAIK v2.0 — MULTI-CEO ARCHITECTURE + 21 SECTIONS")
print("=" * 64)

print("\n=== EXECUTIVE COUNCIL (Multi-CEO Architecture) ===")
print("--- Full Profile (12 CEOs) ---")
check("council starts with full profile", council.profile == "full")
check("full profile has 12 CEOs", council.num_ceos == 12)
ceos = council.list_ceos()
check("Code CEO exists", any(c["id"] == "ceo-code" for c in ceos))
check("Safety CEO exists", any(c["id"] == "ceo-safety" for c in ceos))
check("Creative CEO exists", any(c["id"] == "ceo-creative" for c in ceos))
check("each CEO has managers > 0", all(c["managers"] >= 2 for c in ceos))
check("each CEO has budget string", all("tokens" in c["budget"] for c in ceos))

print("\n--- CEO-to-API Mapping ---")
check("ceo_code owns /v1/route", council.ceo_for_api("/v1/route") == "ceo-code")
check("ceo_ops owns /v1/stats", council.ceo_for_api("/v1/stats") == "ceo-ops")
check("ceo_safety owns /v1/safety", council.ceo_for_api("/v1/safety/pause") == "ceo-safety")
check("ceo_cognition owns /v1/cognitive", council.ceo_for_api("/v1/cognitive/seed") == "ceo-cognition")
check("ceo_corporate owns /v1/library", council.ceo_for_api("/v1/library/search") == "ceo-corporate")
check("ceo_knowledge owns /v1/memory", council.ceo_for_api("/v1/memory") == "ceo-knowledge")

print("\n--- CEO Domain Routing ---")
ceo = council.ceo_for_domain("code")
check("'code' domain routes to Code CEO", ceo.id == "ceo-code")
ceo = council.ceo_for_domain("security")
check("'security' domain routes to Security CEO", ceo.id == "ceo-security")
ceo = council.ceo_for_domain("creative writing")
check("'creative writing' routes to Creative CEO", ceo.id == "ceo-creative")
ceo = council.ceo_for_domain("operations")
check("'operations' routes to Ops CEO", ceo.id == "ceo-ops")

print("\n--- CEO Budget Allocation ---")
budget = council.budget_for("ceo-code")
check("budget_for returns TokenBudget", budget.remaining > 0)
budget2 = council.budget_for("ceo-ops")
check("different CEOs have different budgets", budget.total != budget2.total)

print("\n--- Light Profile (2 CEOs) ---")
council.configure("light")
check("light profile has 2 CEOs", council.num_ceos == 2)
ceos_light = council.list_ceos()
check("Core CEO exists in light", any(c["id"] == "ceo-core" for c in ceos_light))
check("Support CEO exists in light", any(c["id"] == "ceo-support" for c in ceos_light))
ceo = council.ceo_for_domain("code")
check("light: 'code' routes to ceo-core", ceo.id == "ceo-core")
ceo = council.ceo_for_domain("safety")
check("light: 'safety' routes to ceo-support", ceo.id == "ceo-support")
council.configure("full")
check("restored to full profile", council.num_ceos == 12)

print("\n=== Section 1-3: Core Infrastructure ===")
b = TokenBudget(total=100000)
check("budget starts at 100k", b.remaining == 100000)
b.spend(90000); check("economy mode at 10%", b.mode() == "economy")
b.spend(6000); check("survival at 4%", b.mode() == "survival")
b2 = TokenBudget(total=100000)
check("fresh budget can afford full run", b2.enough_for_full_run())

c = Corporate()
check("CEO at depth 0", c.role_at_depth(0) == "CEO")
check("Exec at depth 1", "Exec" in c.role_at_depth(1))
check("Manager at depth 2", c.role_at_depth(2) == "Manager")
check("Permission tier 3 for safety mod", c.permission_tier(0, "modify_safety") == 3)
check("Permission tier 0 for execute", c.permission_tier(0, "execute") == 0)

check("code_writer found for code", experts.find_expert("code") == "code_writer")
check("math_solver found for math", experts.find_expert("math") == "math_solver")
check("synthesizer as fallback", experts.find_expert("unknown") == "synthesizer")

print("\n=== Section 4: Blackboard & Notes ===")
blackboard.write("topic:rust", "Rust is great for systems", "agent-1", 0.9)
check("blackboard read-write", "Rust" in (blackboard.read("topic:rust") or ""))
internal_notes.write("agent-alpha", "Debugging borrow checker", "public", 0.7)
internal_notes.write("agent-beta", "Found race condition", "ceo", 0.9)
check("public notes visible", "agent-alpha" in internal_notes.get_all_public())
check("CEO can read CEO-visible notes", len(internal_notes.read("agent-beta", "CEO", 0)) > 0)
check("worker cannot read CEO-visible notes", len(internal_notes.read("agent-beta", "worker", 5)) == 0)

print("\n=== Section 5: Safety Engine ===")
cb = CircuitBreaker("test", threshold=3, cooldown_s=9999)
cb.record_failure("f1"); cb.record_failure("f2")
check("not tripped after 2", not cb.tripped)
cb.record_failure("f3")
check("tripped after 3", cb.tripped)
check("vibration > 0", cb.vibration() > 0)
triad = SafetyTriad()
triad.record_opinion("p1", "a1", "safe", 0.9)
triad.record_opinion("p1", "a2", "safe", 0.8)
triad.record_opinion("p1", "a3", "unsafe", 0.6)
check("triad majority safe", triad.majority_verdict("p1") == "safe")
sl = StopLight()
check("starts green", sl.status() == "green")
sl.set_yellow(1); check("yellow after set", sl.status() == "yellow")
sl.set_red(1); check("red after set_red", sl.status() == "red")
mc = MonotonicConfidence()
mc.record("h1", "failure", 0.3); mc.record("h1", "failure", 0.3); mc.record("h1", "failure", 0.3)
check("repeat count = 2", mc.repeat_count("h1") == 2)
check("should_skip after 2+", mc.should_skip("h1"))
check("detects API key", len(anti_pattern.check("api_key = 'sk-abc123'")) > 0)
check("clean text passes", len(anti_pattern.check("hello")) == 0)

print("\n=== Section 6: Thought VDB ===")
thought_vdb.inject("agent-1", "Rust ownership prevents races", ["rust", "memory"], 0.8)
results = thought_vdb.query("rust memory", 3)
check("thought vdb returns results", len(results) > 0)
check("incubate adds heat", thought_vdb.incubate(results[0]["id"], 0.5))

print("\n=== Section 8: Memory System ===")
l1 = L1Memory(capacity=10)
l1.store("k1", "Rust is fast", {"confidence": 0.9})
l1.store("k2", "Python is great", {"confidence": 0.8})
check("l1 recall returns results", len(l1.recall("rust fast")) > 0)
l2 = L2Memory(min_confidence=0.7, min_access=3)
entry = {"key": "k1", "value": "important", "access_count": 5, "metadata": {"confidence": 0.9}}
check("l2 consolidates", l2.consider(entry) is not None)
check("l2 marks tier", l2.consider(entry)["tier"] == "L2")
l3_memory.archive({"key": "perm", "value": "core"})
check("l3 recall works", len(l3_memory.recall("core")) > 0)

print("\n=== Section 9: Scheduler ===")
s = CostAwareScheduler(); s.register_agent("worker", 2)
t1 = s.enqueue("urgent", "worker", 50, 1.0)
t2 = s.enqueue("low priority", "worker", 200, 0.1)
check("dequeue returns highest priority", s.dequeue("worker").id == t1)
check("scheduler stats work", "queue_size" in s.stats())

print("\n=== Section 10: Evolution (PBT) ===")
p = PBTEngine(population_size=4)
p.seed({"lr": 0.1, "depth": 5, "temp": 0.7})
check("population seeded", p.stats()["population"] == 4)
p.evolve(); check("generation advances", p.stats()["generation"] >= 1)
check("best config is dict", isinstance(p.best_config(), dict))
rs = RewardShaper()
rs.record("code", True, 5); rs.record("math", False, 2)
check("difficulty tracks", rs.difficulty("code") > rs.difficulty("math"))
check("shaped reward in [0,1]", 0 <= rs.shaped_reward(0.8, "code", 5) <= 1)

print("\n=== Section 11: Meta Controller ===")
m = MetaAgent()
m.register_sub_agent("w1", "specialist", ["code"])
check("delegate returns id", len(m.delegate("w1", "write code")) > 0)
m.complete_task("w1", "success", 0.9)
check("agent status idle", m.stats()["agents"]["w1"]["status"] == "idle")
m.add_prompt("sys", "You are helpful")
check("prompt stored", m.get_prompt("sys") == "You are helpful")
state_machine.set_state("a1", "running")
state_machine.set_state("a1", "completed")
check("state works", state_machine.get_state("a1") == "completed")

print("\n=== Section 12: Expert Bridge ===")
check("experts registered", expert_bridge.stats()["experts"] > 0)
check("graceful error", "error" in expert_bridge.call_expert("nonexistent", {}))

print("\n=== Section 13: Cognitive Engine ===")
incubation.seed("a1", "What if agents reflect?", "meta", ["meta"])
check("percolation returns int", isinstance(incubation.percolate(), int))
abductor.record_pattern("system slow", "CPU bottleneck", 0.8)
check("abductive returns results", len(abductor.best_explanation("system slow")) > 0)
analogizer.record_mapping("sorting", "scheduling", "ordering", 0.8)
check("analogical returns results", len(analogizer.find_analogies("sort list")) > 0)
wanderer.add_association("code", "test")
check("wandering produces path", len(wanderer.wander("code", 2)) >= 2)
check("chunking produces chunks", len(chunker.chunk("First sentence. Second sentence. Third sentence. Fourth. Fifth.", 20)) >= 2)

print("\n=== Section 14: Corporate Library ===")
cl = CorporateLibrary(); ps = PermissionSystem()
cl.register_agent("a1", "specialist"); cl.register_agent("ceo1", "ceo")
lid = cl.contribute("a1", "sort-utils", "def qsort(): pass", "code")
check("contribute returns id", lid is not None)
check("search returns results", len(cl.search("sort", "code")) > 0)
cl.use_library(lid); cl.use_library(lid)
check("usage tracking", cl.stats()["total_usage"] >= 2)
check("CEO can deploy", ps.check("ceo", "deploy"))
check("specialist cannot deploy", not ps.check("specialist", "deploy"))
check("protected blocked for specialist", cl.contribute("a1", "secret", "...", visibility="protected") is None)

print("\n=== Section 15: Purity Filter ===")
check("clean text pure", purity.check("hello")["pure"])
check("malicious blocked", not purity.check("DROP TABLE users")["pure"])
check("API key detected", purity.check("api_key = 'sk-abc123'")["secrets_detected"])
check("violations tracked", purity.violation_count() > 0)

print("\n=== Section 16-17: Route (CEO-aware) ===")
clear_cache()
r = route("write a python function to sort a list", "code", TokenBudget(total=100000))
check("route returns CEO id", "ceo" in r)
check("Code CEO assigned for code problem", r["ceo"] == "ceo-code")
check("route returns CEO name", "ceo_name" in r)
check("route returns CEO budget", "ceo_budget" in r)
check("route returns expert", r["expert"] == "code_writer")
check("first route not cached", not r["cached"])
r2 = route("write a python function to sort a list", "code", TokenBudget(total=100000))
check("second route cached", r2["cached"])
clear_cache()
r3 = route("solve 2x+5=13", "math")
check("math routes to correct CEO", r3["ceo"] in ("ceo-code", "ceo-data"))

print("\n=== Section 18: Boolean Agent Algebra ===")
nv = NeuralVoter()
nv.register_voter("writer", 1.5, 0.0); nv.register_voter("reviewer", 1.0, 0.1)
vresult = nv.vote({"writer": 0.9, "reviewer": 0.7})
check("neural voting returns outcome", "outcome" in vresult)
circuit = AgentCircuit()
g1 = AgentGate("g1", GateOp.AND, inputs=["a","b"], output="c")
g2 = AgentGate("g2", GateOp.NOT, inputs=["c"], output="result")
circuit.add_gate(g1); circuit.add_gate(g2)
circuit.set_input("a", 1.0); circuit.set_input("b", 1.0)
check("circuit AND->NOT = 0", circuit.evaluate().get("g2", -1) == 0)

print("\n=== Section 19-21: Advanced ===")
print("--- Model Chain ---")
check("route uses flash", cfg.pick_model("route", "normal")["name"] == "flash")
check("survival uses flash", cfg.pick_model("execute", "survival")["name"] == "flash")
check("economy caps small", cfg.pick_model("synthesize", "economy")["name"] in ("flash","small"))

print("--- Offline Execute (CEO-aware) ---")
clear_cache(); ob = TokenBudget(total=50000)
result = execute("write hello world", "general", ob, depth=0)
check("execute returns solution", "solution" in result)
check("execute returns ceo", "ceo" in result)
check("execute has agents_used", isinstance(result["agents_used"], list) and len(result["agents_used"]) >= 1)
check("execute has ceo_execution_counts", isinstance(result["ceo_execution_counts"], dict))
check("execute returns budget_mode", "budget_mode" in result)
check("execute returns notes", "notes" in result)
check("execute returns agents_log", len(result.get("agents_log", [])) > 0)

print("--- Routing Log ---")
log = ceo_routing_log()
check("routing log has entries", len(log) >= 0)
check("ceo_execution_breakdown returns dict", isinstance(ceo_execution_breakdown(), dict))

print("--- Self-Improvement Flywheel ---")
learn1 = learn("quicksort", "fn qs(){}", "success",
               [{"role":"code_writer","id":"a1"},{"role":"reviewer","id":"a2"}], 0.95, 2500, 8000)
check("learn returns run_id", "run_id" in learn1)
check("ELO updated > 1200", learn1["elo_updated"].get("code_writer", 0) > 1200)
check("postmortem has worked field", "worked" in learn1["postmortem"])
check("replay queue growing", learn1["replay_queue_size"] >= 1)
learn2 = learn("buggy sort", "", "failure", [{"role":"code_writer","id":"a3"}], 0.3, 500, 2000)
check("ELO penalized for failure", learn2["elo_updated"].get("code_writer", 0) < 1232)

stats = get_stats()
check("stats has total_runs", stats["total_runs"] >= 2)
check("stats has success_rate", 0 <= stats["success_rate"] <= 1)

print("--- Config Sections ---")
check("safety_cfg has threshold", safety_cfg.circuit_breaker_threshold == 3)
check("memory_cfg has l1_capacity", memory_cfg.l1_capacity == 50)
check("cognitive_cfg has heat_rate", cognitive_cfg.incubation_heat_rate == 0.1)
check("evolution_cfg has pop size", evolution_cfg.population_size == 10)

print("\n" + "=" * 64)
total = passed + failed
print(f"RESULTS: {passed}/{total} passed, {failed}/{total} failed")
if failed == 0: print("ALL FEATURES VERIFIED — MULTI-CEO ARCHITECTURE CONFIRMED")
else: print(f"WARNING: {failed} tests failed")
print("=" * 64)
